In [37]:
# importing csv data 
import pandas as pd
df = pd.read_csv('election_results_1976_2024.csv')

df.head()

,Year,State,Region,Democratic %,Republican %,P.S.,P.S. Score,National Winner,State Winner
0,1976,Alabama,South,55.7%,42.6%,D+,11.23,Carter (D),Democrat
1,1980,Alabama,South,47.4%,48.8%,D+,9.26,Reagan (R),Democrat
2,1984,Alabama,South,38.3%,60.5%,R+,-4.19,Reagan (R),Republican
3,1988,Alabama,South,39.9%,59.2%,R+,-11.69,Bush H.W. (R),Republican
4,1992,Alabama,South,40.9%,47.6%,R+,-14.55,Clinton (D),Republican

In [38]:
df

,Year,State,Region,Democratic %,Republican %,P.S.,P.S. Score,National Winner,State Winner
0,1976,Alabama,South,55.7%,42.6%,D+,11.23,Carter (D),Democrat
1,1980,Alabama,South,47.4%,48.8%,D+,9.26,Reagan (R),Democrat
2,1984,Alabama,South,38.3%,60.5%,R+,-4.19,Reagan (R),Republican
3,1988,Alabama,South,39.9%,59.2%,R+,-11.69,Bush H.W. (R),Republican
4,1992,Alabama,South,40.9%,47.6%,R+,-14.55,Clinton (D),Republican
...,...,...,...,...,...,...,...,...,...
658,2008,Washington D.C.,Northeast,92.5%,6.5%,D+,79.42,Obama (D),Democrat
659,2012,Washington D.C.,Northeast,90.9%,7.3%,D+,81.25,Obama (D),Democrat
660,2016,Washington D.C.,Northeast,90.9%,4.1%,D+,89.16,Trump (R),Democrat
661,2020,Washington D.C.,Northeast,92.1%,5.4%,D+,84.39,Biden (D),Democrat
662,2024,Washington D.C.,Northeast,90.3%,6.5%,D+,88.13,Trump (R),Democrat

In [39]:
# Step 1: Strip % and convert
df['Year'] = df['Year'].astype(int)
df['Democratic %'] = pd.to_numeric(df['Democratic %'].str.replace('%', ''), errors='coerce')
df['Republican %'] = pd.to_numeric(df['Republican %'].str.replace('%', ''), errors='coerce')
df['P.S. Score'] = pd.to_numeric(df['P.S. Score'], errors='coerce')

# Step 2: Rename
df.rename(columns={
    'Democratic %': 'dem_pct',
    'Republican %': 'rep_pct',
    'P.S.': 'party_strength',
    'P.S. Score': 'ps_score',
    'National Winner': 'national_winner',
    'State Winner': 'state_winner'
}, inplace=True)

In [40]:
df

,Year,State,Region,dem_pct,rep_pct,party_strength,ps_score,national_winner,state_winner
0,1976,Alabama,South,55.7,42.6,D+,11.23,Carter (D),Democrat
1,1980,Alabama,South,47.4,48.8,D+,9.26,Reagan (R),Democrat
2,1984,Alabama,South,38.3,60.5,R+,-4.19,Reagan (R),Republican
3,1988,Alabama,South,39.9,59.2,R+,-11.69,Bush H.W. (R),Republican
4,1992,Alabama,South,40.9,47.6,R+,-14.55,Clinton (D),Republican
...,...,...,...,...,...,...,...,...,...
658,2008,Washington D.C.,Northeast,92.5,6.5,D+,79.42,Obama (D),Democrat
659,2012,Washington D.C.,Northeast,90.9,7.3,D+,81.25,Obama (D),Democrat
660,2016,Washington D.C.,Northeast,90.9,4.1,D+,89.16,Trump (R),Democrat
661,2020,Washington D.C.,Northeast,92.1,5.4,D+,84.39,Biden (D),Democrat
662,2024,Washington D.C.,Northeast,90.3,6.5,D+,88.13,Trump (R),Democrat